install: refine ouput on error
Before this patch a traceback was shown when subprocess call, that runs
`build.py`, failed. The reason of the error is the output of the build
script rather the `CalledProcessError` exception that only shows
`build.py` failed with a specific `python` version.

This modifications is intended to separate the output of the build
process that gives the user a more specific reason of the error. And
below that the command run.

Before:

```
Please install CMake and retry.
Traceback (most recent call last):
  File "install.py", line 44, in <module>
    Main()
  File "install.py", line 33, in Main
    subprocess.check_call( [ python_binary, build_file ] + sys.argv[1:] )
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['path/to/python', u'path/to/build.py']' returned non-zero exit status 1
```

After:

```
Building ycmd using [path/to/build.py] with python binary at [path/to/python]:
Error message from build.py...

Exception raised:
Command '['path/to/python', u'path/to/build.py']' returned non-zero exit status 1
```

Signed-off-by: Gergő Nagy <grigori.grant@gmail.com>