Patched boost/detail/interlocked.hpp for "undefined reference to `interlocked...`" errors in Mingw-w64
Youcompleteme is not corectly compiled with mingw64 from mingw-builds if build version is greater than 4.8.1-rev1.
Check bug at https://svn.boost.org/trac/boost/ticket/4849#comment:18
I applied changes from https://svn.boost.org/trac/boost/changeset/85865 and it compile successfully now.