Updated paths to the build directory Curenntly causes the following error if you follow the complete guide:
CompletionData.h:23:10: fatal error: 'clang-c/Index.h' file not found
   #include <clang-c/Index.h>